<?php
$helper = $this->helper('Magento\Search\Helper\Data');
?>

<div class="smart-search search-by-category">
    <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
        <?php if($block->enableSearchByCat()){ ?>
        <div class="select-category">    
            <select name="cat" id="choose_category">
                    <option value=""><?php echo __('All Categories'); ?></option>
                <?php $categories = $block->getCategories(); 
                foreach($categories as $cat)
                {
                    if(isset($_GET['cat']) && $_GET['cat'] == $cat->getId()){
                        echo '<option value="'.$cat->getId().'" selected="selected">'.$cat->getName().'</option>';
                    }
                    else{
                        echo '<option value="'.$cat->getId().'">'.$cat->getName().'</option>';
                    }
                }
                ?>
                </select>
        </div>
        <?php } ?>
        <div class="smart-search-form">
            <input id="search-input-autocomplate" data-mage-init='{"quickSearch":{
                        "formSelector":"#search_mini_form",
                        "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest'); ?>",
                        "destinationSelector":"#search_autocomplete"}
                   }' type="text" name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>" value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Search here...'); ?>" class="input-text" maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>" role="combobox" aria-haspopup="false" aria-autocomplete="both"  aria-expanded="false" autocomplete="off" />
            <div id="search_autocomplete" class="search-autocomplete"></div>
            <div data-bind="scope: 'searchsuiteautocomplete_form'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <button type="submit"
                    title="<?php echo $block->escapeHtml(__('Search')) ?>"
            >
                <span><?php echo __('Search'); ?></span>
            </button>
        </div>
    </form>
</div>

<?php if($block->enableSearchByCat()){ ?>
<script type="text/javascript">
    require([
        'jquery',
        'rokanthemes/choose'
    ], function ($) {
        $("#choose_category").chosen();
    });
</script>
<?php } ?>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "searchsuiteautocomplete_form": {
                    "component": "Rokanthemes_SearchSuiteAutocomplete/js/autocomplete"
                },
                "searchsuiteautocompleteBindEvents": {
                    "component": "Rokanthemes_SearchSuiteAutocomplete/js/bindEvents",
                    "config": {
                        "searchFormSelector": "#search_mini_form",
                        "searchButtonSelector": "button.search",
                        "inputSelector": "#search-input-autocomplate",
                        "searchDelay": "<?php echo $block->escapeHtml($block->getSearchDelay()) ?>"
                    }
                },
                "searchsuiteautocompleteDataProvider": {
                    "component": "Rokanthemes_SearchSuiteAutocomplete/js/dataProvider",
                    "config": {
                        "url": "<?php echo $block->escapeUrl($block->getSearchUrl()) ?>"
                    }
                }
            }
        }
    }
}
</script>